name: More Reasonable Emacs

on:
  pull_request:
    branches:
      - cc
  push:
    branches:
      - cc

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # checkout history and tags

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install emacs
      - name: Test
        run: |
          ./test.sh

  MacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # checkout history and tags
      - name: Install Dependencies
        run: |
          brew install emacs
      - name: Test Nore
        run: |
          ./test.sh

  Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # checkout history and tags

    - name: Install Dependencies
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: git make mingw-w64-x86_64-gcc emacs mingw-w64-x86_64

    - name: Test
      run: |
        ./test.sh

# eof
